### ISSUE TITLE
Update to recipes.md

### ISSUE THREAD

**Issue by jasonrhaas** [SonarSource/docker-sonarqube#106]
I noticed this hasn't been updated in a little while, and I think it has become simpler with the newer versions of `docker` and `docker-compose`.

I was able to get it working with this **docker-compose.yml** file.

```
version: "2"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar

  db:
    image: postgres
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
```

Am I missing something?  If not, I'm happy to submit a Pull Request.
