### ISSUE TITLE
Bundled plugins only available on first run with MySQL database

### ISSUE THREAD

**Issue by gdhgdhgdh** [SonarSource/docker-sonarqube#112]
Hullo,

I've been experiencing quite some fun with both the SQ `6.4` and `6.5` images. We have a simple setup:

```
sonarqube:
  image: sonarqube:6.5
  net: host
  environment:
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=ReallySecret123
   - SONARQUBE_JDBC_URL=jdbc:mysql://localhost:43306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true

db:
  image: mysql:5.7.13
  net: host
  environment:
   - MYSQL_ROOT_PASSWORD=Secret456
   - MYSQL_DATABASE=sonar
   - MYSQL_USER=sonar
   - MYSQL_PASSWORD=ReallySecret123
  command: --port=43306
  volumes:
   - /data/sonar-mysql:/var/lib/mysql
```

When I `docker-compose up` for the first time I see the auto deployment of the Java/Python/C#/Git plugins since they are in `bundled-plugins` ...
```
....
sonarqube_1  | 2017.10.19 14:33:26 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarJava [java] installed
sonarqube_1  | 2017.10.19 14:33:26 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin SonarJS [javascript] installed
sonarqube_1  | 2017.10.19 14:33:26 INFO  web[][o.s.s.p.ServerPluginRepository] Plugin C# [csharp] installed
sonarqube_1  | 2017.10.19 14:33:26 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin C# / 5.10.1.1411 / 748a97f89a5327cbea5cfe1f8aebe87d073c74a0
sonarqube_1  | 2017.10.19 14:33:26 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJS / 3.0.0.4962 / d34263e00f57251f23fedeb41b6d76d740f6ba5c
sonarqube_1  | 2017.10.19 14:33:26 INFO  web[][o.s.s.p.ServerPluginRepository] Deploy plugin SonarJava / 4.9.0.9858 / f04d72a01871c96235fa97e0b9c5582455f313da
....
```

I also see the Database schema migrations happening. All good.

SQ works fine first time. Now I hit `CTRL-C` in the `docker-compose` log window, and the containers are stopped. I now `docker-compose down` to destroy the containers. 

The persistent MySQL data still exists in `/data/sonar-mysql`.

When I `docker-compose up` again, SQ starts up, but I see hundreds of lines like tthis:

```
sonarqube_1  | 2017.10.19 14:35:03 INFO  web[][o.s.s.r.RegisterRules] Disable rule Pylint:R0801
sonarqube_1  | 2017.10.19 14:35:03 INFO  web[][o.s.s.r.RegisterRules] Disable rule squid:UselessParenthesesCheck
sonarqube_1  | 2017.10.19 14:35:03 INFO  web[][o.s.s.r.RegisterRules] Disable rule squid:RightCurlyBraceSameLineAsNextBlockCheck
sonarqube_1  | 2017.10.19 14:35:03 INFO  web[][o.s.s.r.RegisterRules] Disable rule javascript:S138
sonarqube_1  | 2017.10.19 14:35:03 INFO  web[][o.s.s.r.RegisterRules] Disable rule squid:S1764
sonarqube_1  | 2017.10.19 14:35:03 INFO  web[][o.s.s.r.RegisterRules] Disable rule csharpsquid:S112
sonarqube_1  | 2017.10.19 14:35:03 INFO  web[][o.s.s.r.RegisterRules] Disable rule csharpsquid:S110
```

Further, when I browse to http://localhost:9000/profiles - instead of the previous list of languages, the list is completely empty - literally `No results`

Is this expected? Have I made a silly assumption about how SQ works?

The only way I've been able to make it work consistently is to copy the existing `lib/bundled-plugins/*.jar` into `extensions/plugins`, and that feels really wrong!
