### ISSUE TITLE
Cannot start sonarqube with mysql

### ISSUE THREAD

**Issue by YordanBorisov** [SonarSource/docker-sonarqube#122]
```
sonar:
  build: .
  ports:
   - "9000:9000"
  links:
   - mysql:mysql
  environment:
   - ADOP_LDAP_ENABLED=false
   - SONARQUBE_JDBC_USERNAME=sonar
   - SONARQUBE_JDBC_PASSWORD=sonar
   - SONARQUBE_JDBC_URL=jdbc:mysql://mysql:3306/sonar?useUnicode=true&characterEncoding=utf8&rewriteBatchedStatements=true
mysql:
 image: mysql:5.7
 environment:
  - MYSQL_USER=sonar
  - MYSQL_PASSWORD=sonar
  - MYSQL_DATABASE=sonar
  - MYSQL_ROOT_PASSWORD=sonar
 ports:
  - "3306:3306"
```
and I get for sonar  in docker logs:
```
error: database is uninitialized and password option is not specified 
  You need to specify one of MYSQL_ROOT_PASSWORD, MYSQL_ALLOW_EMPTY_PASSWORD and MYSQL_RANDOM_ROOT_PASSWORD
```

and mysql container is running normal.
