### ISSUE TITLE
SonarQube container on CentOS

### ISSUE THREAD

**Issue by davidlaughlin** [SonarSource/docker-sonarqube#130]
Hi,

We have a CentOS server running Docker that we are trying to run SonarQube on.  When I run the container, it starts up but then hangs after 'HTTP Connector enabled on port 9000'.  If I navigate to the url in a browser I just get a TomCat error page.

Is SonarQube container supported on CentOS? Any suggestions on debugging steps?

Thanks.

```
20:40:01.035 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
2017.11.28 20:40:01 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2017.11.28 20:40:01 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2017.11.28 20:40:01 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2017.11.28 20:40:01 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2017.11.28 20:40:01 INFO  app[][o.e.p.PluginsService] no modules loaded
2017.11.28 20:40:01 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2017.11.28 20:40:09 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2017.11.28 20:40:09 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:./lib/server/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.1.1.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process372844261423375785properties
2017.11.28 20:40:10 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2017.11.28 20:40:10 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2017.11.28 20:40:10 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
2017.11.28 20:43:52 INFO  app[][o.s.a.SchedulerImpl] Stopping SonarQube
2017.11.28 20:43:52 INFO  web[][o.s.p.StopWatcher] Stopping process
2017.11.28 20:43:52 INFO  app[][o.s.a.SchedulerImpl] Process [web] is stopped
2017.11.28 20:43:52 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
2017.11.28 20:43:52 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
2017.11.28 20:43:52 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 143
20:43:58.618 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
2017.11.28 20:43:58 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2017.11.28 20:43:58 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2017.11.28 20:43:58 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch -Epath.conf=/opt/sonarqube/temp/conf/es
2017.11.28 20:43:58 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2017.11.28 20:43:59 INFO  app[][o.e.p.PluginsService] no modules loaded
2017.11.28 20:43:59 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
2017.11.28 20:44:07 INFO  app[][o.s.a.SchedulerImpl] Process[es] is up
2017.11.28 20:44:07 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:./lib/server/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.1.1.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process5202420815524590070properties
2017.11.28 20:44:08 INFO  web[][o.s.p.ProcessEntryPoint] Starting web
2017.11.28 20:44:08 INFO  web[][o.a.t.u.n.NioSelectorPool] Using a shared selector for servlet write/read
2017.11.28 20:44:09 INFO  web[][o.s.s.a.EmbeddedTomcat] HTTP connector enabled on port 9000
```

**Comment by nixel2007** [comment]
Could you post your docker-compose file or docker run command?

**Comment by davidlaughlin** [comment]
CentOS Version: CentOS Linux release 7.2.1511 (Core)
Docker Version: Docker version 17.09.0-ce, build afdb6d4

```
sonarqube:
  image: sonarqube:6.7
  container_name: sonarqube
  environment:
    #- VIRTUAL_HOST=sonar.example.com
    #- VIRTUAL_PORT=9000
    - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db_1:5432/sonar
  ports:
    - "9000:9000"
  links:
    - sonarqube_db_1
  volumes:
    - /var/lib/docker/app/sonarqube/conf:/opt/sonarqube/conf
    - /var/lib/docker/app/sonarqube/data:/opt/sonarqube/data
    - /var/lib/docker/app/sonarqube/extensions:/opt/sonarqube/extensions
    - /var/lib/docker/app/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
    - /var/lib/docker/app/sonarqube/temp:/opt/sonarqube/temp
    - /var/lib/docker/app/sonarqube/web:/opt/sonarqube/web

sonarqube_db_1:
  image: postgres
  container_name: sonarqube_db_1
  environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=sonar
  volumes:
    - /var/lib/docker/app/sonarqube/postgresql/data/:/var/lib/postgresql/data
    - /var/lib/docker/app/sonarqube/postgresql_data/:/var/lib/postgresqldata
```
