### ISSUE TITLE
How to provide jdbc oracle driver to image that we pulled.

### ISSUE THREAD

**Issue by AtulKamra** [SonarSource/docker-sonarqube#14]
We have downloaded the sonarqube image and trying to run it by using below command. 

docker run -d --name sonarqube -p 9000:9000 -p 9092:9092 -e SONARQUBE_JDBC_USERNAME=X -e SONARQUBE_JDBC_PASSWORD=Y -e SONARQUBE_JDBC_URL=jdbc:oracle:thin://Z.Z.Z.Z:P/orcl sonarqube:5.1

where X = Is my oracle RDS user name.
where Y = Is my oracle RDS password.
Z.Z.Z.Z = IP address of my oracle RDS
P = Port # of my oracle RDS.
orcl = SID name of my oracle RDS.

Whenever I run this command I get error when I check the logs of container. 
Not able to find the driver in extensions/jdbc-driver/oracle folder.

How can we copy the driver in this folder inside docker?

**Comment by Godin** [comment]
@AtulKamra as an idea - use [docker-compose](https://docs.docker.com/compose/), something like:
create `docker-compose.yml`
```
sonarqube:
  image: "sonarqube"
  ports:
   - "9000:9000"
  volumes_from:
   - plugins

plugins:
  build: "."
  volumes:
   - /opt/sonarqube/extensions
   - /opt/sonarqube/lib/bundled-plugins
  command: /bin/true
```
create `Dockerfile`
```
FROM sonarqube
COPY jar_with_driver.jar /opt/sonarqube/extensions/jdbc-driver/oracle
```
start the containers
```
docker-compose up
```
