### ISSUE TITLE
Cannot start service sonarqube: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./bin/run.sh\": stat ./bin/run.sh: no such file or directory": unknown

### ISSUE THREAD

**Issue by purbayanto** [SonarSource/docker-sonarqube#197]
docker-compose.yml

```
version: "3"

services:
  sonarqube:
    image: sonarqube:6.7.5
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=v07IGCFCF83Z95NX
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
      - "9000:9000"
      - "9092:9092"
    volumes:
      - ./docker/sonarqube:/opt/sonarqube
      - ./docker/sonarqube/temp:/opt/sonarqube/temp
      - ./docker/sonarqube/conf:/opt/sonarqube/conf
      - ./docker/sonarqube/data:/opt/sonarqube/data
      - ./docker/sonarqube/extensions:/opt/sonarqube/extensions
      - ./docker/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:10.1
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=v07IGCFCF83Z95NX
      - POSTGRES_DB=sonarqube
    volumes:
      - ./docker/sonarqube_db:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./docker/sonarqube_db/data:/var/lib/postgresql/data

```

i got an error when installing sonarqube

```
ERROR: for tiket_sonarqube_1  Cannot start service sonarqube: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./bin/run.sh\": stat ./bin/run.sh: no such file or directory": unknown

ERROR: for sonarqube  Cannot start service sonarqube: OCI runtime create failed: container_linux.go:348: starting container process caused "exec: \"./bin/run.sh\": stat ./bin/run.sh: no such file or directory": unknown
ERROR: Encountered errors while bringing up the project.
```

this is the full log

```
$ docker-compose -f docker-compose-sonar.yml up -d
Pulling sonarqube (sonarqube:6.7.5)...
6.7.5: Pulling from library/sonarqube
55cbf04beb70: Already exists
1607093a898c: Already exists
9a8ea045c926: Already exists
d4eee24d4dac: Already exists
c58988e753d7: Already exists
794a04897db9: Already exists
70fcfa476f73: Already exists
806029475e0c: Pull complete
67959b355155: Pull complete
9c5d1232dc0d: Pull complete
93ff21b61fc7: Pull complete
8aca50099d16: Pull complete
3074d41df515: Pull complete
Digest: sha256:ab43a9ad7fc060be3db740ba419b666ab16b6d31c0c55b98018422829e428b1d
Status: Downloaded newer image for sonarqube:6.7.5
Creating tiket_sonarqube_1 ... error
Creating tiket_db_1        ... done
```
