### ISSUE TITLE
Latest SonarQube image is not compatible with any postgres image

### ISSUE THREAD

**Issue by prashanth-sams** [SonarSource/docker-sonarqube#237]
### Error:
```
SonarQube is offline
The connection to SonarQube is lost. Please contact your system administrator.
```

### **docker-compose.yml**

```
version: "3"

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    restart: always
    environment:
    - SONARQUBE_JDBC_USERNAME=sonar
    - SONARQUBE_JDBC_PASSWORD=password1
    - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonarqube
    ports:
    - "9000:9000"
    - "9092:9092"
    volumes:
    - sonarqube_conf:/opt/sonarqube/conf
    - sonarqube_data:/opt/sonarqube/data
    - sonarqube_extensions:/opt/sonarqube/extensions
    - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:9.5
    container_name: db
    restart: always
    environment:
    - POSTGRES_USER=sonar
    - POSTGRES_PASSWORD=password1
    - POSTGRES_DB=sonarqube
    volumes:
    - sonarqube_db:/var/lib/postgresql
    - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql_data:
  sonarqube_bundled-plugins:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_db:
  sonarqube_extensions:
```
### Screenshot
![image](https://user-images.githubusercontent.com/2948696/51541679-db8bfb80-1e72-11e9-8ae1-0f50563667fe.png)
