### ISSUE TITLE
java.lang.OutOfMemoryError: GC overhead limit exceeded

### ISSUE THREAD

**Issue by montge** [SonarSource/docker-sonarqube#245]
Tried to use docker compose for starting system.  It's unclear if memory is being allocated correctly as shows the following in the startup log.

```2019.02.15 02:41:30 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='web', ipcIndex=2, logFilenamePrefix=web]] from [/opt/sonarqube]: /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -server -Xmx2g -Xms2g -Djava.security.egd=file:/dev/./urandom -cp ./lib/common/*:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.5.jar org.sonar.server.app.WebServer /opt/sonarqube/temp/sq-process4358976241854045374properties```

and I get the following error, this occurs with large code bases.

```
2019.02.15 14:10:39 INFO  ce[AWjxfcPnKtOvhKsrHmsp][o.s.c.t.s.ComputationStepExecutor] Compute Quality Profile status | status=SUCCESS | time=8ms
java.lang.OutOfMemoryError: GC overhead limit exceeded
Dumping heap to java_pid211.hprof ...
Heap dump file created [608599131 bytes in 5.979 secs]
2019.02.15 14:11:44 INFO  ce[AWjxfcPnKtOvhKsrHmsp][o.s.c.t.s.ComputationStepExecutor] Execute component visitors | status=FAILED | time=64895ms
2019.02.15 14:11:47 ERROR ce[AWjxfcPnKtOvhKsrHmsp][o.s.c.t.CeWorkerImpl] Failed to execute task AWjxfcPnKtOvhKsrHmsp
java.lang.OutOfMemoryError: GC overhead limit exceeded
	at org.sonar.db.protobuf.DbIssues$Location.toBuilder(DbIssues.java:2181)
	at org.sonar.db.protobuf.DbIssues$Location.newBuilder(DbIssues.java:2175)
```

with a docker compose of

```
version: "2"

services:
  sonarqube:
    image: sonarqube
    command: -Dsonar.ce.javaOpts=-Xmx2048m -Dsonar.web.javaOpts=-Xmx2048m
    expose:
      - 9000
    ports:
      - "127.0.0.1:9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
```
