### ISSUE TITLE
SonarQube crashed when start docker-compose with sonarqube:7.9-community

### ISSUE THREAD

**Issue by danbao** [SonarSource/docker-sonarqube#285]
Error Logs

```bash
[root@hello word]# docker logs sonarqube -f
2019.07.08 06:23:42 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
2019.07.08 06:23:42 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
2019.07.08 06:23:43 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
2019.07.08 06:23:43 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2019.07.08 06:23:43 INFO  app[][o.e.p.PluginsService] no modules loaded
2019.07.08 06:23:43 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
#
# A fatal error has been detected by the Java Runtime Environment:
#
#  SIGILL (0x4) at pc=0x00007faf54628537, pid=33, tid=257
#
# JRE version: OpenJDK Runtime Environment (11.0.3+7) (build 11.0.3+7)
# Java VM: OpenJDK 64-Bit Server VM (11.0.3+7, mixed mode, tiered, compressed oops, concurrent mark sweep gc, linux-amd64)
# Problematic frame:
# J 5073 c2 com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer.calcHash([II)I (115 bytes) @ 0x00007faf54628537 [0x00007faf54628420+0x0000000000000117]
#
# Core dump will be written. Default location: /opt/sonarqube/elasticsearch/core.33
#
[thread 262 also had an error]
[thread 219 also had an error]
[thread 260 also had an error]
[thread 258 also had an error]
# An error report file with more information is saved as:
# ../logs/es_hs_err_pid33.log
[thread 259 also had an error]
Compiled method (c1)   17957 4003       3       com.fasterxml.jackson.core.sym.ByteQuadsCanonicalizer::findName (198 bytes)
 total in heap  [0x00007faf4d9cc110,0x00007faf4d9cd040] = 3888
 relocation     [0x00007faf4d9cc288,0x00007faf4d9cc370] = 232
 main code      [0x00007faf4d9cc380,0x00007faf4d9ccb40] = 1984
 stub code      [0x00007faf4d9ccb40,0x00007faf4d9ccc48] = 264
 oops           [0x00007faf4d9ccc48,0x00007faf4d9ccc50] = 8
 metadata       [0x00007faf4d9ccc50,0x00007faf4d9ccc60] = 16
 scopes data    [0x00007faf4d9ccc60,0x00007faf4d9ccd80] = 288
 scopes pcs     [0x00007faf4d9ccd80,0x00007faf4d9ccfd0] = 592
 dependencies   [0x00007faf4d9ccfd0,0x00007faf4d9ccfd8] = 8
 nul chk table  [0x00007faf4d9ccfd8,0x00007faf4d9cd040] = 104
Could not load hsdis-amd64.so; library not loadable; PrintAssembly is disabled
#
# If you would like to submit a bug report, please visit:
#   http://bugreport.java.com/bugreport/crash.jsp
#
2019.07.08 06:24:03 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 134
2019.07.08 06:24:03 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
2019.07.08 06:24:03 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
```

docker-compose.yml
```yml
version: "3"

services:
  sonarqube:
    image: sonarqube:7.9-community
    command: -Dsonar.ce.javaOpts=-Xmx8192m -Dsonar.web.javaOpts=-Xmx8192m
    restart: unless-stopped
    container_name: sonarqube
    depends_on:
      - sonarqube_db
    ports:
      - "9000:9000"
    networks:
      - sonar-net
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://sonarqube_db:5432/sonar
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  sonarqube_db:
    image: postgres
    container_name: sonarqube_db
    restart: unless-stopped
    networks:
      - sonar-net
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - "/data/sonarqube/postgresql:/var/lib/postgresql"
      - "/data/sonarqube/postgresql_data:/var/lib/postgresql/data"

networks:
  sonar-net:
    external: true

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
```

docker info
```bash
Containers: 27
 Running: 27
 Paused: 0
 Stopped: 0
Images: 207
Server Version: 18.09.7
Storage Driver: overlay2
 Backing Filesystem: xfs
 Supports d_type: true
 Native Overlay Diff: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host ipvlan macvlan null overlay
 Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
init version: fec3683
Security Options:
 seccomp
  Profile: default
Kernel Version: 5.0.2-1.el7.elrepo.x86_64
Operating System: CentOS Linux 7 (Core)
OSType: linux
Architecture: x86_64
CPUs: 48
Total Memory: 377.9GiB
Name: xia01-i01-dck02.lab.rcch.ringcentral.com
ID: BAMX:AP3R:KWCW:RAJ6:JIZY:HMGJ:5LEL:UV6R:C5LM:OPA6:GUGT:72P3
Docker Root Dir: /opt/docker
Debug Mode (client): false
Debug Mode (server): true
 File Descriptors: 236
 Goroutines: 206
 System Time: 2019-07-08T02:32:22.582442535-04:00
 EventsListeners: 0
Registry: https://index.docker.io/v1/
Labels:
Experimental: true
Insecure Registries:
 127.0.0.0/8
Registry Mirrors:
 https://registry.docker-cn.com/
Live Restore Enabled: false
Product License: Community Engine
```

**Comment by pierre-guillot-sonarsource** [comment]
Hello,

Your docker-compose work for me with few modification :
- using less memory `-Dsonar.ce.javaOpts=-Xmx1192m -Dsonar.web.javaOpts=-Xmx1192m`
- using named volume instead of direct binding : 
```
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
```

With the declaration of theses in the volume list at the end :
```
volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:
```

Could you please try this, starting with an empty db ?
