### ISSUE TITLE
lcov.info file not recognizing file paths when using Github Actions

### ISSUE THREAD

**Issue by TheBusyBiscuit** [SonarSource/docker-sonarqube#328]
## Description
I am trying to sonarscan a JavaScript project of mine.
I am using "nyc" to generate the lcov coverage-report, but Sonarcloud fails to read that file.
Or the file paths in my lcov.info file to be precise.

Can anyone help me find a way to fix it?
The github action for this has it's own repository but Issues are disabled, so I've come to what I think might be the closest related repository to it.

## Attachements
I am using v1.1 of sonarcloud-github-action (latest at this time)
https://github.com/sonarsource/sonarcloud-github-action

Here is my workflow.yml file:
https://raw.githubusercontent.com/TheBusyBiscuit/builds/gh-pages/.github/workflows/sonar.yml

Here is the error that pops up in the log:
```
INFO: Analysing [/github/workspace/./coverage/lcov.info]
WARN: Could not resolve 7 file paths in [/github/workspace/./coverage/lcov.info], first unresolved path: /home/runner/work/builds/builds/src/config.js
INFO: Sensor SonarJS Coverage [javascript] (done) | time=11ms
```

**Comment by pierre-guillot-sonarsource** [comment]
@simonbrandhof can you please have a look ? :)

**Comment by simonbrandhof** [comment]
Hi, as described in https://github.com/sonarsource/sonarcloud-github-action, feedback should be posted on https://community.sonarsource.com/ with the tag `sonarcloud`. 
Thanks

**Comment by DaveKlassen** [comment]
I'm having this issue as well

**Comment by hakimio** [comment]
@TheBusyBiscuit did you ever resolve the issue? Using same `sonar-project.properties` file and excuting `sonar-scanner` locally it works fine, but running from GitHub action I get the same `Could not resolve file paths` error.

**Comment by jagadish10** [comment]
> @TheBusyBiscuit did you ever resolve the issue? Using same `sonar-project.properties` file and excuting `sonar-scanner` locally it works fine, but running from GitHub action I get the same `Could not resolve file paths` error.

@hakimio did you got any solution for this
I also facing the same issue

**Comment by hakimio** [comment]
Yeah, I guess I did with some code coverage path replacements:
```yml
jobs:
  sonar-cloud-scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: install dependencies
        working-directory: ./frontend
        run: yarn install
      - name: create code coverage report
        working-directory: ./frontend
        run: yarn test --coverage
      - name: fix code coverage paths
        working-directory: ./frontend/coverage
        run: |
          sed -i 's/\/home\/runner\/work\/YOUR_PROJECT_ROOT_DIR\/YOUR_PROJECT_ROOT_DIR\//\/github\/workspace\//g' lcov.info
          sed -i 's/\/home\/runner\/work\/YOUR_PROJECT_ROOT_DIR\/YOUR_PROJECT_ROOT_DIR\//\/github\/workspace\//g' sonar-cloud-reporter.xml
      - name: SonarCloud Scan
        uses: hakimio/sonarcloud-github-action@pr-fix
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
```

Also, using custom github sonarcloud github action with [this fix](https://github.com/hakimio/sonarcloud-github-action/commit/9e1b3369fbc00366b00b456eee6d662ea9ecd5a1). Don't remember exactly why it was necessary. Maybe because it wasn't re-running the analysis on PR commit push.
