### ISSUE TITLE
Missing dependencies for installing SonarJava related plugins

### ISSUE THREAD

**Issue by prodigy7** [SonarSource/docker-sonarqube#331]
I try to install the "Code Smells" which needs SonarJava. Installing SonarJava runs into a error
```sonarqube /usr/local/openjdk-11/lib/libfontmanager.so: libfreetype.so.6:```
and prevent container from working! Would be nice if needed dependencies would be added to ``Dockerfile``

Image: sonarqube:7.9.1-community

**Comment by pierre-guillot-sonarsource** [comment]
Good morning @michal-duda-sonarsource :) Can you please have a look to this ?

**Comment by michal-duda-sonarsource** [comment]
@prodigy7 just tried it and I'm not getting any errors when installing SonarJava from Marketplace using that image. How and which version of SonarJava are you trying to install? 

Also, what do you mean by "Code Smells"?

**Comment by prodigy7** [comment]
> @prodigy7 just tried it and I'm not getting any errors when installing SonarJava from Marketplace using that image. How and which version of SonarJava are you trying to install?
> 
> Also, what do you mean by "Code Smells"?

Sorry for the missing details! I've created a fresh sonarqube installation and install then over the administration the "Code Smells" plugin. After restart I got the error i have described.

**Comment by michal-duda-sonarsource** [comment]
I can't reproduce it, this plugin installs correctly on my machine. Can you provide all the docker commands you are using to run the container? Are you using the Marketplace to install both SonarJava and Code Smells? Which OS are you using as host?

**Comment by Jaff** [comment]
I am getting the same issue, running container sonarqube:7.9.1-community. I had it running, then realized no plugins, so I added all the ones I needed and restart exposed the above issue (among others)

**Comment by prodigy7** [comment]
My docker-compose.yml:

```
version: "2"

services:
  sonarqube:
    image: sonarqube:7.9.1-community
    restart: always
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
      - SONARQUBE_JDBC_PASSWORD=...
    volumes:
      - /opt/docker/sonarqube/conf:/opt/sonarqube/conf
      - /opt/docker/sonarqube/data:/opt/sonarqube/data
      - /opt/docker/sonarqube/extensions:/opt/sonarqube/extensions
      - /opt/docker/sonarqube/logs:/opt/sonarqube/logs
      #- /opt/docker/sonarqube/lib/bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres:12.0
    restart: always
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=...
    volumes:
      - /opt/docker/sonarqube/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - /opt/docker/sonarqube/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_bundled-plugins:
  postgresql:
  postgresql_data:

```
