### ISSUE TITLE
docker start fails with es log permission

### ISSUE THREAD

**Issue by bewell** [SonarSource/docker-sonarqube#353]
Hey all, 

I'm trying to run a sonarqube docker instance on AWS EC2, here's my yaml file:

```yaml
version: "3"


services:
  sonarqube:
    image: sonarqube
    ports:
     - "9000:9000"
     - "5432:5432"
    links:
      - db:db
    environment:
     - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
     - SONARQUBE_JDBC_USERNAME=postgres
     - SONARQUBE_JDBC_PASSWORD=sonar
    volumes:
     - ....../docker_storages/sonarqube_sast/sonarqube/conf:/opt/sonarqube/conf
     - ....../docker_storages/sonarqube_sast/sonarqube/logs:/opt/sonarqube/logs
     - ....../docker_storages/sonarqube_sast/sonarqube/data:/opt/sonarqube/data
     - ....../docker_storages/sonarqube_sast/sonarqube/extensions:/opt/sonarqube/extensions
     - ....../docker_storages/sonarqube_sast/sonarqube/bundled-plugins:/opt/sonarqube/lib/bundled-plugins


  db:
    image: postgres
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=sonar
     - POSTGRES_DB=sonar
    volumes:
     - ....../docker_storages/sonarqube_sast/postgres:/var/lib/postgresql
     # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
     - ....../docker_storages/sonarqube_sast/postgres/data:/var/lib/postgresql/data
```

Then I'm starting the db with 
```
docker-compose up -d db
```

Everything works fine until here. Then I'm starting Sonarqube to actually see what's happening and the process stops with this error:
```
sonarqube_1  | 2019.11.27 13:01:29 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
sonarqube_1  | 2019.11.27 13:01:30 INFO  app[][o.e.p.PluginsService] no modules loaded
sonarqube_1  | 2019.11.27 13:01:30 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
sonarqube_1  | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
sonarqube_1  | 2019-11-27 13:01:32,880 main ERROR Unable to create file /opt/sonarqube/logs/es.log java.io.IOException: Permission denied
sonarqube_1  | 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
```
What am I doing wrong?

Thanks!
