### ISSUE TITLE
Install sonar by Docker

### ISSUE THREAD

**Issue by RemDav** [SonarSource/docker-sonarqube#402]
Hi everybode,

I am trying to install sonarqube lts or 8.3 with docker. It is impossible to install. Here are the logs:

`2020.05.04 08:57:11 WARN  es[][o.e.b.JNANatives] unable to install syscall filter: 
java.lang.UnsupportedOperationException: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
	at org.elasticsearch.bootstrap.SystemCallFilter.linuxImpl(SystemCallFilter.java:342) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.SystemCallFilter.init(SystemCallFilter.java:617) ~[elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.JNANatives.tryInstallSystemCallFilter(JNANatives.java:260) [elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.Natives.tryInstallSystemCallFilter(Natives.java:113) [elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.Bootstrap.initializeNatives(Bootstrap.java:108) [elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:170) [elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:333) [elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159) [elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150) [elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86) [elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124) [elasticsearch-cli-6.8.0.jar:6.8.0]
	at org.elasticsearch.cli.Command.main(Command.java:90) [elasticsearch-cli-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116) [elasticsearch-6.8.0.jar:6.8.0]
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93) [elasticsearch-6.8.0.jar:6.8.0]
2020.05.04 08:57:12 INFO  es[][o.e.e.NodeEnvironment] using [1] data paths, mounts [[/opt/sonarqube/data (/dev/vg1/volume_1)]], net usable_space [2.3tb], net total_space [2.6tb], types [ext4]
2020.05.04 08:57:12 INFO  es[][o.e.e.NodeEnvironment] heap size [503.6mb], compressed ordinary object pointers [true]
2020.05.04 08:57:12 INFO  es[][o.e.n.Node] node name [sonarqube], node ID [iC35JzQhS22OVvdAkTwWOQ]
2020.05.04 08:57:12 INFO  es[][o.e.n.Node] version[6.8.0], pid[20], build[default/tar/65b6179/2019-05-15T20:06:13.172855Z], OS[Linux/3.10.105/amd64], JVM[Oracle Corporation/OpenJDK 64-Bit Server VM/11.0.7/11.0.7+10]
2020.05.04 08:57:12 INFO  es[][o.e.n.Node] JVM arguments [-XX:+UseConcMarkSweepGC, -XX:CMSInitiatingOccupancyFraction=75, -XX:+UseCMSInitiatingOccupancyOnly, -Des.networkaddress.cache.ttl=60, -Des.networkaddress.cache.negative.ttl=10, -XX:+AlwaysPreTouch, -Xss1m, -Djava.awt.headless=true, -Dfile.encoding=UTF-8, -Djna.nosys=true, -XX:-OmitStackTraceInFastThrow, -Dio.netty.noUnsafe=true, -Dio.netty.noKeySetOptimization=true, -Dio.netty.recycler.maxCapacityPerThread=0, -Dlog4j.shutdownHookEnabled=false, -Dlog4j2.disable.jmx=true, -Djava.io.tmpdir=/opt/sonarqube/temp, -XX:ErrorFile=../logs/es_hs_err_pid%p.log, -Des.enforce.bootstrap.checks=true, -Xms512m, -Xmx512m, -XX:+HeapDumpOnOutOfMemoryError, -Des.path.home=/opt/sonarqube/elasticsearch, -Des.path.conf=/opt/sonarqube/temp/conf/es, -Des.distribution.flavor=default, -Des.distribution.type=tar]
2020.05.04 08:57:14 INFO  es[][o.e.p.PluginsService] loaded module [analysis-common]
2020.05.04 08:57:14 INFO  es[][o.e.p.PluginsService] loaded module [lang-painless]
2020.05.04 08:57:14 INFO  es[][o.e.p.PluginsService] loaded module [mapper-extras]
2020.05.04 08:57:14 INFO  es[][o.e.p.PluginsService] loaded module [parent-join]
2020.05.04 08:57:14 INFO  es[][o.e.p.PluginsService] loaded module [percolator]
2020.05.04 08:57:14 INFO  es[][o.e.p.PluginsService] loaded module [reindex]
2020.05.04 08:57:14 INFO  es[][o.e.p.PluginsService] loaded module [repository-url]
2020.05.04 08:57:14 INFO  es[][o.e.p.PluginsService] loaded module [transport-netty4]
2020.05.04 08:57:14 INFO  es[][o.e.p.PluginsService] no plugins loaded
2020.05.04 08:57:20 WARN  es[][o.e.d.c.s.Settings] [http.enabled] setting was deprecated in Elasticsearch and will be removed in a future release! See the breaking changes documentation for the next major version.
2020.05.04 08:57:22 INFO  es[][o.e.d.DiscoveryModule] using discovery type [zen] and host providers [settings]
2020.05.04 08:57:23 INFO  es[][o.e.n.Node] initialized
2020.05.04 08:57:23 INFO  es[][o.e.n.Node] starting ...
2020.05.04 08:57:24 INFO  es[][o.e.t.TransportService] publish_address {127.0.0.1:9001}, bound_addresses {127.0.0.1:9001}
2020.05.04 08:57:24 INFO  es[][o.e.b.BootstrapChecks] explicitly enforcing bootstrap checks
2020.05.04 08:57:24 ERROR es[][o.e.b.Bootstrap] node validation exception
[1] bootstrap checks failed
[1]: system call filters failed to install; check the logs and fix your configuration or disable system call filters at your own risk
2020.05.04 08:57:24 INFO  es[][o.e.n.Node] stopping ...
2020.05.04 08:57:24 INFO  es[][o.e.n.Node] stopped
2020.05.04 08:57:24 INFO  es[][o.e.n.Node] closing ...
2020.05.04 08:57:24 INFO  es[][o.e.n.Node] closed`

I also change the system conf like this :
sysctl -w vm.max_map_count=262144
sysctl -w fs.file-max=65536
ulimit -n 65536
ulimit -u 2048

**Comment by michal-duda-sonarsource** [comment]
I don't think this is Docker specific. Please have a look at [SonarQube docs](https://docs.sonarqube.org/latest/requirements/requirements/#header-4) (search for `seccomp filter`). Adding environment variable SONAR_SEARCH_JAVAADDITIONALOPTS="-Dbootstrap.system_call_filter=false" should resolve the issue. 

Please reopen if that doesn't fix the issue.

**Comment by pplmx** [comment]
Hi, @michal-duda-sonarsource 
It doesn't work.
Here is my docker-compose.yml
```yaml
version: "3"

services:
    sonarqube:
        image: sonarqube:community
        platform: linux/x86_64
        depends_on:
            - db
        environment:
            SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
            SONAR_JDBC_USERNAME: sonar
            SONAR_JDBC_PASSWORD: sonar
            SONAR_SEARCH_JAVAADDITIONALOPTS: -Dbootstrap:system_call_filter=false
        volumes:
            - sonarqube_data:/opt/sonarqube/data
            - sonarqube_extensions:/opt/sonarqube/extensions
            - sonarqube_logs:/opt/sonarqube/logs
        ports:
            - "9000:9000"
    db:
        image: postgres:12
        platform: linux/x86_64
        environment:
            POSTGRES_USER: sonar
            POSTGRES_PASSWORD: sonar
        volumes:
            - postgresql:/var/lib/postgresql
            - postgresql_data:/var/lib/postgresql/data

volumes:
    sonarqube_data:
    sonarqube_extensions:
    sonarqube_logs:
    postgresql:
    postgresql_data:

```
