### ISSUE TITLE
WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 1

### ISSUE THREAD

**Issue by mlem** [SonarSource/docker-sonarqube#408]
Probably related to #263

Hello, I'm in the middle of an upgrade process.
We are upgrading sonarqube from 6.1 to 8.x.
As described in https://docs.sonarqube.org/latest/setup/upgrading/ we are hopping from
6.1 -> 6.7.7 LTS -> 7.9.x LTS -> 8.1.

Until now we've arrived at 6.7.7 LTS with only minor issues.
Now we try to upgrade our sonar from it to 7.9.3-community.

The plan was to use docker-compose scripts to make this process easier.
```
version: "3"
services:
  sonarqube:
    image: library/sonarqube:7.9.3-community
    container_name: sonarqube
    hostname: sonarqube
    expose:
      - 9000
    user: "999"
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar # jdbc:postgresql://db/sonar in example
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
networks:
  sonarnet:
    external:
      name: sonar_network
```

```
Creating sonarqube ... done
Attaching to sonarqube
sonarqube    | tail: cannot open './logs/es.log' for reading: No such file or directory
sonarqube    | 06:37:56.427 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
sonarqube    | 2020.05.15 06:37:56 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
sonarqube    | 2020.05.15 06:37:56 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
sonarqube    | 2020.05.15 06:37:56 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
sonarqube    | 2020.05.15 06:37:56 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
sonarqube    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
sonarqube    | 2020.05.15 06:37:56 INFO  app[][o.e.p.PluginsService] no modules loaded
sonarqube    | 2020.05.15 06:37:56 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
sonarqube    | 2020.05.15 06:37:58 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 1
sonarqube    | 2020.05.15 06:37:58 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
sonarqube    | 2020.05.15 06:37:58 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
sonarqube    | tail: './logs/es.log' has appeared;  following new file
sonarqube exited with code 0
```

Ok, to fix this `tail: './logs/es.log' has appeared;  following new file` issue I'm adding the logs folder as volume.

```
version: "3"
services:
  sonarqube:
    image: library/sonarqube:7.9.3-community
    container_name: sonarqube
    hostname: sonarqube
    expose:
      - 9000
    user: "999"
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar # jdbc:postgresql://db/sonar in example
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
      - ./sonarqube_logs:/opt/sonarqube/logs
networks:
  sonarnet:
    external:
      name: sonar_network
```

```
Recreating sonarqube ... done
Attaching to sonarqube
sonarqube    | tail: cannot open './logs/es.log' for reading: No such file or directory
sonarqube    | 06:38:29.021 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
sonarqube    | 2020.05.15 06:38:29 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
sonarqube    | 2020.05.15 06:38:29 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
sonarqube    | 2020.05.15 06:38:29 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
sonarqube    | 2020.05.15 06:38:29 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
sonarqube    | 2020.05.15 06:38:29 INFO  app[][o.e.p.PluginsService] no modules loaded
sonarqube    | 2020.05.15 06:38:29 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
sonarqube    | OpenJDK 64-Bit Server VM warning: Option UseConcMarkSweepGC was deprecated in version 9.0 and will likely be removed in a future release.
sonarqube    | 2020-05-15 06:38:30,503 main ERROR Unable to create file /opt/sonarqube/logs/es.log java.io.IOException: Permission denied
sonarqube    | 	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
sonarqube    | 	at java.base/java.io.File.createNewFile(Unknown Source)
sonarqube    | 	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:628)
sonarqube    | 	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:608)
sonarqube    | 	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:113)
sonarqube    | 	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
sonarqube    | 	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:188)
sonarqube    | 	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:145)
sonarqube    | 	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:61)
sonarqube    | 	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:123)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
sonarqube    | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
sonarqube    | 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
sonarqube    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:234)
sonarqube    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:127)
sonarqube    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:302)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
sonarqube    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
sonarqube    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
sonarqube    | 	at org.elasticsearch.cli.Command.main(Command.java:90)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
sonarqube    | 
sonarqube    | 2020-05-15 06:38:30,506 main ERROR Could not create plugin of type class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@4612b856] unable to create manager for [/opt/sonarqube/logs/es.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@22875539[pattern=/opt/sonarqube/logs/es.%d{yyyy-MM-dd}.log, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=true)]), strategy=DefaultRolloverStrategy(min=-2147483648, max=2147483647, useMax=false), advertiseURI=null, layout=%d{yyyy.MM.dd HH:mm:ss} %-5level es[][%logger{1.}] %msg%n, filePermissions=null, fileOwner=null]] java.lang.IllegalStateException: ManagerFactory [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory@4612b856] unable to create manager for [/opt/sonarqube/logs/es.log] with data [org.apache.logging.log4j.core.appender.rolling.RollingFileManager$FactoryData@22875539[pattern=/opt/sonarqube/logs/es.%d{yyyy-MM-dd}.log, append=true, bufferedIO=true, bufferSize=8192, policy=CompositeTriggeringPolicy(policies=[TimeBasedTriggeringPolicy(nextRolloverMillis=0, interval=1, modulate=true)]), strategy=DefaultRolloverStrategy(min=-2147483648, max=2147483647, useMax=false), advertiseURI=null, layout=%d{yyyy.MM.dd HH:mm:ss} %-5level es[][%logger{1.}] %msg%n, filePermissions=null, fileOwner=null]]
sonarqube    | 	at org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:115)
sonarqube    | 	at org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:114)
sonarqube    | 	at org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:188)
sonarqube    | 	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:145)
sonarqube    | 	at org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:61)
sonarqube    | 	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:123)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
sonarqube    | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
sonarqube    | 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
sonarqube    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:234)
sonarqube    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:127)
sonarqube    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:302)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
sonarqube    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
sonarqube    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
sonarqube    | 	at org.elasticsearch.cli.Command.main(Command.java:90)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
sonarqube    | 
sonarqube    | 2020-05-15 06:38:30,507 main ERROR Unable to invoke factory method in class org.apache.logging.log4j.core.appender.RollingFileAppender for element RollingFile: java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender java.lang.IllegalStateException: No factory method found for class org.apache.logging.log4j.core.appender.RollingFileAppender
sonarqube    | 	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.findFactoryMethod(PluginBuilder.java:235)
sonarqube    | 	at org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:135)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:959)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:899)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:891)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:514)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:238)
sonarqube    | 	at org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:250)
sonarqube    | 	at org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:547)
sonarqube    | 	at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:263)
sonarqube    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:234)
sonarqube    | 	at org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:127)
sonarqube    | 	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:302)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.init(Elasticsearch.java:159)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.execute(Elasticsearch.java:150)
sonarqube    | 	at org.elasticsearch.cli.EnvironmentAwareCommand.execute(EnvironmentAwareCommand.java:86)
sonarqube    | 	at org.elasticsearch.cli.Command.mainWithoutErrorHandling(Command.java:124)
sonarqube    | 	at org.elasticsearch.cli.Command.main(Command.java:90)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:116)
sonarqube    | 	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:93)
sonarqube    | 
sonarqube    | 2020-05-15 06:38:30,507 main ERROR Null object returned for RollingFile in Appenders.
sonarqube    | 2020-05-15 06:38:30,508 main ERROR Unable to locate appender "file_es" for logger config "root"
sonarqube    | 2020.05.15 06:38:30 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 1
sonarqube    | 2020.05.15 06:38:30 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
sonarqube    | 2020.05.15 06:38:30 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
sonarqube exited with code 0
```

Hmm, doesn't work. Maybe I need to take some previous version?
Downgrading to 7.7-community

```
version: "3"
services:
  sonarqube:
    image: library/sonarqube:7.7-community
    container_name: sonarqube
    hostname: sonarqube
    expose:
      - 9000
    user: "999"
    ports:
      - 9000:9000
    networks:
      - sonarnet
    environment:
      - sonar.jdbc.url=jdbc:postgresql://db:5432/sonar # jdbc:postgresql://db/sonar in example
      - sonar.jdbc.username=sonar
      - sonar.jdbc.password=sonar
    volumes:
      - ./sonarqube_conf:/opt/sonarqube/conf
      - ./sonarqube_data:/opt/sonarqube/data
      - ./sonarqube_extensions:/opt/sonarqube/extensions
networks:
  sonarnet:
    external:
      name: sonar_network
```

```
Creating sonarqube ... done
Attaching to sonarqube
sonarqube    | 06:21:31.977 [main] WARN org.sonar.application.config.AppSettingsLoaderImpl - Configuration file not found: /opt/sonarqube/conf/sonar.properties
sonarqube    | 2020.05.15 06:21:32 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
sonarqube    | 2020.05.15 06:21:32 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on /127.0.0.1:9001
sonarqube    | 2020.05.15 06:21:32 INFO  app[][o.s.a.p.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
sonarqube    | 2020.05.15 06:21:32 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
sonarqube    | 2020.05.15 06:21:32 INFO  app[][o.e.p.PluginsService] no modules loaded
sonarqube    | 2020.05.15 06:21:32 INFO  app[][o.e.p.PluginsService] loaded plugin [org.elasticsearch.transport.Netty4Plugin]
sonarqube    | 2020.05.15 06:21:33 WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
sonarqube    | 2020.05.15 06:21:33 INFO  app[][o.s.a.SchedulerImpl] Process [es] is stopped
sonarqube    | 2020.05.15 06:21:33 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
sonarqube exited with code 0
```

Still doesn't work.
The only line which always appears with a hint what isn't working is this one:
```
WARN  app[][o.s.a.p.AbstractProcessMonitor] Process exited with exit value [es]: 1
```
