### ISSUE TITLE
expose conf and logs directory as docker volume

### ISSUE THREAD

**Issue by andreyhsiao** [SonarSource/docker-sonarqube#44]
exposing conf and logs directory as docker volume

**Comment by LorenzoBettini** [comment]
I don't know if this is related to the fact that conf is not exposed as a docker volume, but if I modify the docker-compose.yml file in order to mount volumes in my host as follows:

```
version: "2"

services:
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db:5432/sonar
    volumes:
      - ./volumes/sonarqube_conf:/opt/sonarqube/conf
      - ./volumes/sonarqube_data:/opt/sonarqube/data
      - ./volumes/sonarqube_extensions:/opt/sonarqube/extensions
      - ./volumes/sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins

  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
      # This needs explicit mapping due to https://github.com/docker-library/postgres/blob/4e48e3228a30763913ece952c611e5e9b95c8759/Dockerfile.template#L52
      - ./volumes/postgresql_data:/var/lib/postgresql/data

networks:
  sonarnet:
    driver: bridge
```

then, the directories "conf" and "bundled-plugins" are created on my host (inside the automatically created "volumes" directory), but they're empty and they stay empty (so Sonarqube is run without any plugin installed).

If I use the docker-compose.yml exactly as shown in https://github.com/SonarSource/docker-sonarqube/blob/master/recipes.md then the named volumes are correctly filled: you have the default configuration and the default bundled-plugins.  Why does that happen?
