### ISSUE TITLE
Process exited with exit value [es]

### ISSUE THREAD

**Issue by yidasanqian** [SonarSource/docker-sonarqube#508]
docker-compose.yml
```
version: '3'
services:
  postgres:
    image: postgres
    restart: always
    container_name: postgres
    user: postgres
    ports:
      - 5432:5432
    volumes:
      - ./postgres/postgresql:/var/lib/postgresql
      - ./postgres/data:/var/lib/postgresql/data
    environment:
      TZ: Asia/Shanghai
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
  sonar:
    image: sonarqube
    container_name: sonar  
    privileged: true 
    depends_on:
      - postgres
    volumes:
      - ./extensions:/opt/sonarqube/extensions
      - ./logs:/opt/sonarqube/logs
      - ./data:/opt/sonarqube/data
      #- ./conf:/opt/sonarqube/conf
    ports:
      - 9002:9000
    command:
      - -Dsonar.ce.javaOpts=-Xmx2048m
      - -Dsonar.web.javaOpts=-Xmx2048m
    environment:
      TZ: Asia/Shanghai
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonar
      SONARQUBE_JDBC_URL: jdbc:postgresql://postgres:5432/sonar
```
sonar.log
```
Attaching to postgres, sonar
postgres    |
postgres    | PostgreSQL Database directory appears to contain a database; Skipping initialization
postgres    |
postgres    | 2021-10-12 14:03:56.842 CST [1] LOG:  starting PostgreSQL 14.0 (Debian 14.0-1.pgdg110+1) on x86_64-pc-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit
postgres    | 2021-10-12 14:03:56.843 CST [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
postgres    | 2021-10-12 14:03:56.843 CST [1] LOG:  listening on IPv6 address "::", port 5432
postgres    | 2021-10-12 14:03:56.849 CST [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
postgres    | 2021-10-12 14:03:56.874 CST [13] LOG:  database system was shut down at 2021-10-12 14:03:49 CST
postgres    | 2021-10-12 14:03:56.905 CST [1] LOG:  database system is ready to accept connections
sonar       | 2021.10.12 14:03:58 INFO  app[][o.s.a.AppFileSystem] Cleaning or creating temp directory /opt/sonarqube/temp
sonar       | 2021.10.12 14:03:58 INFO  app[][o.s.a.es.EsSettings] Elasticsearch listening on [HTTP: 127.0.0.1:9001, TCP: 127.0.0.1:38511]
sonar       | 2021.10.12 14:03:58 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='es', ipcIndex=1, logFilenamePrefix=es]] from [/opt/sonarqube/elasticsearch]: /opt/sonarqube/elasticsearch/bin/elasticsearch
sonar       | 2021.10.12 14:03:58 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
sonar       | 2021.10.12 14:03:58 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 137
sonar       | 2021.10.12 14:03:58 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
sonar       | 2021.10.12 14:03:59 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
sonar exited with code 0
```

what reason ?
