### ISSUE TITLE
Examples not in sync with documentation

### ISSUE THREAD

**Issue by eest** [SonarSource/docker-sonarqube#530]
Please ensure your issue adheres to the following guidelines: 

This repository is used for technical issues only. For general Support like questions, please create a new Thread in our [Community Forum](https://community.sonarsource.com/)

- [x] Please check the problem is not already reported, or a known issue documented in [`develop.md`](develop.md)
- [x] Please include enough details to reproduce the problem: the command executed, the host platform, error messages or relevant logs

Hello,

The compose example at https://docs.sonarqube.org/latest/setup/install-server/ currently looks like this:
```
version: "3"

services:
  sonarqube:
    image: sonarqube:community
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:12
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
```

This does not match the setup described at https://github.com/SonarSource/docker-sonarqube/blob/master/examples.md and in the compose examples under https://github.com/SonarSource/docker-sonarqube/tree/master/example-compose-files

Compared with the files I looked at in this repo, the above is different in a few ways:
* `version: "3"` instead of `version: "2"`
* The `sonarqube_temp` volume is not created
* The `sonarnet` network is not created/used.

It would be nice to make it more clear what is expected in the standard case, maybe the docs at https://docs.sonarqube.org/latest/setup/install-server/ should just point to this repo instead of keeping its own example YAML?
