### ISSUE TITLE
Sonarqube starts and then crashes

### ISSUE THREAD

**Issue by PerProjBackup** [SonarSource/docker-sonarqube#536]
I'm running in a Digital Ocean Ubuntu 20.04 (LTS) x64) Droplet.     (2GB/2 CPUs, 60 GB disk)

DOCKER-COMPOSE 1.29.2

I've increased vm to 262144               sysctl -w vm.max_map_count=262144 

I run my docker-compose.yml				docker-compose up -d

docker-compose.yml:
```
docker-compose.yml:
version: '2'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8080:8080"
      - "50000:50000"
    networks:
      - jenkins
    volumes:
      - /var/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
  postgres:
    image: postgres:14.1-alpine
    networks:
      - jenkins
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonarpasswd
    volumes:
      - /var/postgres-data:/var/lib/postgresql/data
  sonarqube:
    image: sonarqube:lts
    ports:
      - "9000:9000"
      - "9092:9092"
    networks:
      - jenkins
    environment:
      SONARQUBE_JDBC_USERNAME: sonar
      SONARQUBE_JDBC_PASSWORD: sonarpasswd
      SONARQUBE_JDBC_URL: "jdbc:postgresql://postgres:5432/sonar"
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs      
    depends_on: 
      - postgres

volumes:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgres-data:

networks:
  jenkins:
```

**Sonarqube starts and then crashes at this point:**
sonarqube_1  | 2022.02.02 17:10:03 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 137

sonarqube log:
. . .
sonarqube_1  | 2022.02.02 17:06:21 INFO  web[][o.s.s.p.p.PlatformLevelStartup] Running Community Edition
sonarqube_1  | 2022.02.02 17:06:21 INFO  web[][o.s.s.p.Platform] WebServer is operational
sonarqube_1  | 2022.02.02 17:06:21 INFO  app[][o.s.a.SchedulerImpl] Process[web] is up
sonarqube_1  | 2022.02.02 17:06:21 INFO  app[][o.s.a.ProcessLauncherImpl] Launch process[[key='ce', ipcIndex=3, logFilenamePrefix=ce]] from [/opt/sonarqube]: /opt/java/openjdk/bin/java -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djava.io.tmpdir=/opt/sonarqube/temp -XX:-OmitStackTraceInFastThrow --add-opens=java.base/java.util=ALL-UNNAMED -Xmx512m -Xms128m -XX:+HeapDumpOnOutOfMemoryError -Dhttp.nonProxyHosts=localhost|127.*|[::1] -cp ./lib/sonar-application-8.9.6.50800.jar:/opt/sonarqube/lib/jdbc/postgresql/postgresql-42.2.19.jar org.sonar.ce.app.CeServer /opt/sonarqube/temp/sq-process14342917442993840287properties
sonarqube_1  | 2022.02.02 17:06:21 INFO  web[][o.s.s.q.ProjectsInWarningDaemon] Counting number of projects in warning will be disabled as there are no more projects in warning.
sonarqube_1  | 2022.02.02 17:06:22 INFO  ce[][o.s.p.ProcessEntryPoint] Starting ce
sonarqube_1  | 2022.02.02 17:06:22 INFO  ce[][o.s.ce.app.CeServer] Compute Engine starting up...
sonarqube_1  | 2022.02.02 17:06:23 INFO  ce[][o.s.s.e.EsClientProvider] Connected to local Elasticsearch: [http://localhost:9001]
sonarqube_1  | 2022.02.02 17:06:25 INFO  ce[][o.sonar.db.Database] Create JDBC data source for jdbc:postgresql://postgres:5432/sonar
sonarqube_1  | 2022.02.02 17:07:55 WARN  es[][o.e.t.ThreadPool] timer thread slept for [6s/6092ms] on absolute clock which is above the warn threshold of [5000ms]
sonarqube_1  | 2022.02.02 17:08:32 WARN  es[][o.e.t.ThreadPool] timer thread slept for [6s/6092135051ns] on relative clock which is above the warn threshold of [5000ms]
sonarqube_1  | 2022.02.02 17:08:32 WARN  es[][o.e.t.ThreadPool] execution of [ReschedulingRunnable{runnable=org.elasticsearch.monitor.jvm.JvmGcMonitorService$1@630eed76, interval=1s}] took [13614ms] which is above the warn threshold of [5000ms]
sonarqube_1  | 2022.02.02 17:08:34 WARN  es[][o.e.t.ThreadPool] timer thread slept for [1.1m/71759ms] on absolute clock which is above the warn threshold of [5000ms]
sonarqube_1  | 2022.02.02 17:08:34 WARN  es[][o.e.t.ThreadPool] timer thread slept for [1.1m/71759564575ns] on relative clock which is above the warn threshold of [5000ms]
sonarqube_1  | 2022.02.02 17:08:45 WARN  es[][o.e.m.f.FsHealthService] health check of [/opt/sonarqube/data/es7/nodes/0] took [7483ms] which is above the warn threshold of [5s]
sonarqube_1  | 2022.02.02 17:09:14 WARN  es[][o.e.t.ThreadPool] execution of [ReschedulingRunnable{runnable=org.elasticsearch.monitor.jvm.JvmGcMonitorService$1@630eed76, interval=1s}] took [6760ms] which is above the warn threshold of [5000ms]
sonarqube_1  | 2022.02.02 17:09:38 WARN  es[][o.e.t.ThreadPool] timer thread slept for [6.9s/6971ms] on absolute clock which is above the warn threshold of [5000ms]
sonarqube_1  | 2022.02.02 17:09:47 WARN  es[][o.e.t.ThreadPool] timer thread slept for [6.9s/6971627432ns] on relative clock which is above the warn threshold of [5000ms]
sonarqube_1  | 2022.02.02 17:09:56 WARN  es[][o.e.t.ThreadPool] timer thread slept for [17.1s/17136ms] on absolute clock which is above the warn threshold of [5000ms]
sonarqube_1  | 2022.02.02 17:10:03 WARN  app[][o.s.a.p.AbstractManagedProcess] Process exited with exit value [es]: 137
sonarqube_1  | 2022.02.02 17:10:03 INFO  app[][o.s.a.SchedulerImpl] Process[es] is stopped
sonarqube_1  | 2022.02.02 17:10:03 INFO  ce[][o.s.p.ProcessEntryPoint] Hard stopping process
sonarqube_1  | 2022.02.02 17:10:04 WARN  ce[][o.s.p.ProcessEntryPoint$HardStopperThread] Can not stop in 1000ms
sonarqube_1  | 2022.02.02 17:10:06 INFO  ce[][o.s.s.p.ServerFileSystemImpl] SonarQube home: /opt/sonarqube
sonarqube_1  | 2022.02.02 17:10:06 INFO  ce[][o.s.c.c.CePluginRepository] Load plugins
sonarqube_1  | 2022.02.02 17:10:09 INFO  ce[][o.s.c.c.ComputeEngineContainerImpl] Running Community edition
sonarqube_1  | 2022.02.02 17:10:09 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is operational
sonarqube_1  | 2022.02.02 17:10:09 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopping...
sonarqube_1  | 2022.02.02 17:10:09 INFO  ce[][o.s.c.t.CeProcessingSchedulerImpl] Hard stopping workers...
sonarqube_1  | 2022.02.02 17:10:11 INFO  ce[][o.s.ce.app.CeServer] Compute Engine is stopped
sonarqube_1  | 2022.02.02 17:10:11 INFO  app[][o.s.a.SchedulerImpl] Process[ce] is stopped
sonarqube_1  | 2022.02.02 17:10:11 INFO  web[][o.s.p.ProcessEntryPoint] Hard stopping process
sonarqube_1  | 2022.02.02 17:10:11 INFO  web[][o.s.s.n.NotificationDaemon] Notification service stopped
sonarqube_1  | 2022.02.02 17:10:11 INFO  app[][o.s.a.SchedulerImpl] Process[web] is stopped
sonarqube_1  | 2022.02.02 17:10:11 INFO  app[][o.s.a.SchedulerImpl] SonarQube is stopped
jenkins_sonarqube_1 exited with code 0

This works on Docker Desktop for Windows with WSL 2.

They are both Linux environments. Is there something special about Ubuntu that needs to considered?
