### ISSUE TITLE
Add curl to container to allow native Docker healthchecks

### ISSUE THREAD

**Issue by binaryfire** [SonarSource/docker-sonarqube#621]
Hi all

Would it be possible to add `curl` to the Docker image? This would allow us to use native Docker healthchecks instead of relying on external bash scripts. I.e. we'd be able to do this:

```
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://localhost:9000/api/system/status | grep -q -e '\"status\":\"UP\"' -e '\"status\":\"DB_MIGRATION_NEEDED\"' -e '\"status\":\"DB_MIGRATION_RUNNING\"' || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 5
```

This is a much better solution than using an external script, since it allows Docker to manage restart attempts etc.
