### ISSUE TITLE
SonarQube docker: wrong ownership of mounted volumn

### ISSUE THREAD

**Issue by WestFarmer** [SonarSource/docker-sonarqube#632]
**docker version: 20.10.12
docker composer version: v2.18.1**

Hi, I built a custom image from latest SonarQube image.

```
FROM sonarqube
ARG version
ARG jar_name
ARG source_path
COPY ./.tmp/${jar_name} ${source_path}
```

then running with such docker compose script:

```
version: "3"
services:
  sonarqube:
    image: 172.25.128.67:9002/sonarqube-bgz
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - /home/sonar/sonarqube/vols/sonar/data:/opt/sonarqube/data
      - /home/sonar/sonarqube/vols/sonar/extensions:/opt/sonarqube/extensions
      - /home/sonar/sonarqube/vols/sonar/logs:/opt/sonarqube/logs
    ports:
      - "9000:9000"
  db:
    image: postgres:15
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - /home/sonar/sonarqube/vols/pg/conf:/var/lib/postgresql
      - /home/sonar/sonarqube/vols/pg/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
```

but fails with log:

```
2023.07.04 14:22:35 INFO  app[][o.s.a.SchedulerImpl] Waiting for Elasticsearch to be up and running
2023-07-04 14:22:39,212 main ERROR Unable to create file /opt/sonarqube/logs/es.log java.io.IOException: Permission denied
	at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
	at java.base/java.io.File.createNewFile(Unknown Source)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:735)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.appender.rolling.RollingFileManager$RollingFileManagerFactory.createManager(RollingFileManager.java:718)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.appender.AbstractManager.getManager(AbstractManager.java:144)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.appender.OutputStreamManager.getManager(OutputStreamManager.java:100)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.appender.rolling.RollingFileManager.getFileManager(RollingFileManager.java:217)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:135)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.appender.RollingFileAppender$Builder.build(RollingFileAppender.java:62)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.config.plugins.util.PluginBuilder.build(PluginBuilder.java:124)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.config.AbstractConfiguration.createPluginObject(AbstractConfiguration.java:1138)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1063)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.config.AbstractConfiguration.createConfiguration(AbstractConfiguration.java:1055)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.config.AbstractConfiguration.doConfigure(AbstractConfiguration.java:664)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.config.AbstractConfiguration.initialize(AbstractConfiguration.java:258)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.config.AbstractConfiguration.start(AbstractConfiguration.java:304)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.LoggerContext.setConfiguration(LoggerContext.java:621)
	at org.apache.logging.log4j.core@8.6.1/org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:285)
	at org.elasticsearch.server@8.6.1/org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:244)
	at org.elasticsearch.server@8.6.1/org.elasticsearch.common.logging.LogConfigurator.configure(LogConfigurator.java:126)
	at org.elasticsearch.server@8.6.1/org.elasticsearch.bootstrap.Elasticsearch.initPhase1(Elasticsearch.java:127)
	at org.elasticsearch.server@8.6.1/org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:62)

```

I change permission of volumn's local dir from 775 to 777, now sonrqube container can start up successfully.

and folders created by sonarqube inside mounted volumn have ownership of test:test.

why is this happen?
