### ISSUE TITLE
permissions issues with 9.9

### ISSUE THREAD

**Issue by zg2pro** [SonarSource/docker-sonarqube#646]
Hello,

I migrated from 8.9 to 9.9 community version and when starting the docker image, I systematically get this error:
```
sonarqube      | java.lang.IllegalStateException: Unable to access 'path.data' (/opt/sonarqube/data/es7)
sonarqube      | Likely root cause: java.nio.file.AccessDeniedException: /opt/sonarqube/data/es7
sonarqube      |        at java.base/sun.nio.fs.UnixException.translateToIOException(Unknown Source)
sonarqube      |        at java.base/sun.nio.fs.UnixException.rethrowAsIOException(Unknown Source)
```

It seems the user sonarqube that runs the application inside of the docker image lacks permissions. I've tried adding 777 permissions to the volume from the host and it has no effect. Also when trying to run docker as root, it says ES can't be run as root. So I'm stuck. Can you please tell me what to do?

Here is my docker-compose:
```
version: "3"
services:
  sonarqube:
    image: my-registry/archi/sonarqube:9.9
    container_name: sonarqube
    privileged: true
    user: sonarqube
    depends_on:
      - init
    ulimits:
      nproc: 131072
      nofile:
        soft: 8192
        hard: 131072
    environment:      
      - "SONAR_JDBC_URL: jdbc:postgresql://xyz.com:5432/sonarqube"
      - "SONAR_JDBC_USERNAME: db_user"
      - "SONAR_JDBC_PASSWORD: xxxxxxxxxxxxxxxxx"
    volumes:
      - "/opt/sonarqube/conf/sonar.properties:/opt/sonarqube/conf/sonar.properties"
      - "/opt/sonarqube/data:/opt/sonarqube/data"
      - "/opt/sonarqube/extensions:/opt/sonarqube/extensions"
      - "/opt/sonarqube/logs:/opt/sonarqube/logs"
    ports:
      - "9000:9000"
```

Thank you for your help!

Best regards
Gregory
