### ISSUE TITLE
Page is not opening

### ISSUE THREAD

**Issue by charlesasilva61** [SonarSource/docker-sonarqube#65]
I installed the Sonarqube6.2 using docker, but the page "Quality Profiles" is not opening.
The page show me a waiting image and not open.

![sonar](https://cloud.githubusercontent.com/assets/24963317/21726847/a1b4ff7c-d425-11e6-85d4-6db60f2d7bce.png)

I notice this happen when I use volumes, below is my docker-compose.yml

```
version: '2'

services:
  sonarqube:
    image: 'sonarqube:6.2'
    ports:
      - '9000:9000'
      - '9092:9092'
    volumes:
       - /home/user/docker/sonar/conf:/opt/sonarqube/conf
       - /home/user/docker/sonar/conf/data:/opt/sonarqube/data
       - /home/user/docker/sonar/conf/extensions:/opt/sonarqube/extensions
       - /home/user/docker/sonar/conf/bundled-plugins:/opt/sonarqube/lib/bundled-plugins
```

2 - If I don't use volumes, what I'll lost?
Can you help me?
