### ISSUE TITLE
java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by montge** [SonarSource/docker-sonarqube#77]
Looking for recommendations on the best way to adjust the Java Heap when using the docker-compose.  We're getting with a large project a java memory error

`java.lang.OutOfMemoryError: Java heap space`

It looks like the following is being set by default.

`-Xmx512m -Xms128m`

Are there specific environmental variables that should be updated, we've been trying some including `SONARQUBE_WEB_JVM_OPTS`

**Comment by Godin** [comment]
Properties mentioned in https://github.com/SonarSource/sonarqube/blob/5.6.6/sonar-application/src/main/assembly/conf/sonar.properties that control JVM options of underlying processes (`sonar.web.javaOpts`, `sonar.ce.javaOpts` and `sonar.search.javaOpts`) can be passed as following
```
docker run -d sonarqube -Dsonar.ce.javaOpts=-Xmx2048m -Dsonar.web.javaOpts=-Xmx2048m
```

and equivalent of this in a docker-compose notation:

```
version: "2"

services:
  sonarqube:
    image: sonarqube
    command: -Dsonar.ce.javaOpts=-Xmx2048m -Dsonar.web.javaOpts=-Xmx2048m
```
