### ISSUE TITLE
Add a way to configure JVM options for Compute Engine

### ISSUE THREAD

**Issue by rsvoboda** [SonarSource/docker-sonarqube#83]
Right now I can configure SONARQUBE_WEB_JVM_OPTS (https://github.com/SonarSource/docker-sonarqube/blob/master/6.3.1/run.sh#L14) to tune JVM for Web Server. There is no way to configure JVM for Compute Engine.

I suggest to introduce SONARQUBE_CE_JVM_OPTS property.

**Comment by Godin** [comment]
Properties mentioned in https://github.com/SonarSource/sonarqube/blob/5.6.6/sonar-application/src/main/assembly/conf/sonar.properties that control JVM options of underlying processes (sonar.web.javaOpts, sonar.ce.javaOpts and sonar.search.javaOpts) can be passed as following
```
docker run -d sonarqube -Dsonar.ce.javaOpts=-Xmx2048m
```
and equivalent of this in a docker-compose notation:
```
version: "2"

services:
  sonarqube:
    image: sonarqube
    command: -Dsonar.ce.javaOpts=-Xmx2048m
```
