### ISSUE TITLE
Volume for plugins

### ISSUE THREAD

**Issue by DblK** [SonarSource/docker-sonarqube#99]
Could you add a volume to $SONARQUBE_HOME/extensions/plugins?
That way, we could install new plugins without having to build a new image based on that one.

Same goes for config folder

**Comment by Godin** [comment]
Quoting https://github.com/SonarSource/docker-sonarqube/issues/75#issuecomment-318041086 :

We removed declaration of volume for directory `extensions` in 80366e3419d698b4bba4447f153418ef64b3b705 for the very good reasons after discussion in https://github.com/docker-library/official-images/pull/2437#issuecomment-266578986

And AFAIK absence of explicit declaration of volume does not prevent externalization of this directory:

```
$ docker run -v /tmp/sonarqube/extensions:/opt/sonarqube/extensions sonarqube
```

or using `docker-compose`:
```
version: "2"

services:
  sonarqube:
    image: sonarqube
    volumes:
      - ./extensions:/opt/sonarqube/extensions
```

Same goes for config folder.
